# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SwiftUIStarter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CleverTap-iOS-SDK', '5.0.1'

  target 'NotificationService' do
    pod 'CTNotificationService'
  end

end
