# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIStarter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CleverTap-iOS-SDK', :path =>'../'
  
  target 'NotificationService' do
    pod 'CTNotificationService'
  end

  target 'NotificationContent' do
    pod 'CTNotificationContent'
  end

  target 'SwiftUIStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUIStarterUITests' do
    # Pods for testing
  end

  post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'CLEVERTAP_HOST_WATCHOS=1']
      end
    end
  end

end
