runs:
  using: "composite"
  steps:
     - name: Run tests
       shell: bash
       run: xcodebuild test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -workspace CleverTapSDK.xcworkspace -scheme CleverTapSDKTests -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' -enableCodeCoverage YES
       
     # - uses: kishikawakatsumi/xcresulttool@v1
       # with:
       #   path: '/Users/runner/work/clevertap-ios-sdk/clevertap-ios-sdk/TestResults.xcresult'
       #   show-code-coverage: true
       # if: success() || failure()
