#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef CLEVERTAPSDK_SWIFT_H
#define CLEVERTAPSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CleverTapSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class NSError;
@class NSData;
SWIFT_CLASS_NAMED("AESGCMCrypt") SWIFT_AVAILABILITY(tvos,introduced=13.0) SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface CTAESGCMCrypt : NSObject
- (nonnull instancetype)initWithKeychainTag:(NSString * _Nonnull)keychainTag OBJC_DESIGNATED_INITIALIZER;
/// Encrypts a string and returns a base64 encoded string with a prefix and suffix.
- (NSString * _Nullable)encryptString:(NSString * _Nonnull)message error:(NSError * _Nullable * _Nullable)errorPointer SWIFT_WARN_UNUSED_RESULT;
/// Encrypts data using AES-GCM and returns a formatted string.
- (NSString * _Nullable)encryptData:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)errorPointer SWIFT_WARN_UNUSED_RESULT;
/// Decrypts an encrypted string and returns the original string.
- (NSString * _Nullable)decryptString:(NSString * _Nonnull)encryptedString error:(NSError * _Nullable * _Nullable)errorPointer SWIFT_WARN_UNUSED_RESULT;
/// Decrypts an encrypted string and returns the original data.
- (NSData * _Nullable)decryptData:(NSString * _Nonnull)encryptedString error:(NSError * _Nullable * _Nullable)errorPointer SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("CTAppRatingHelper")
@interface CTAppRatingHelper : NSObject
+ (void)requestRatingWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CTTimerResult;
SWIFT_CLASS("_TtC12CleverTapSDK18CTCancelledJobData")
@interface CTCancelledJobData : NSObject
@property (nonatomic, readonly) NSTimeInterval originalDelay;
@property (nonatomic, readonly) NSTimeInterval scheduledAt;
- (nonnull instancetype)initWithOriginalDelay:(NSTimeInterval)originalDelay scheduledAt:(NSTimeInterval)scheduledAt callback:(void (^ _Nonnull)(CTTimerResult * _Nonnull))callback OBJC_DESIGNATED_INITIALIZER;
- (void)invokeCallbackWith:(CTTimerResult * _Nonnull)result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class InAppTimerManager;
@protocol InAppSchedulingStrategy;
@protocol InAppDataExtractor;
/// Unified scheduler that combines timer management with storage strategy
/// Can be used for both delayed and in-action features
SWIFT_CLASS("_TtC12CleverTapSDK16CTInAppScheduler")
@interface CTInAppScheduler : NSObject
- (nonnull instancetype)initWithTimerManager:(InAppTimerManager * _Nonnull)timerManager storageStrategy:(id <InAppSchedulingStrategy> _Nullable)storageStrategy dataExtractor:(id <InAppDataExtractor> _Nullable)dataExtractor OBJC_DESIGNATED_INITIALIZER;
/// Schedule multiple in-apps with appropriate storage strategy
- (void)scheduleInApps:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)inApps onComplete:(void (^ _Nonnull)(id _Nullable))onComplete;
/// Get active count
- (void)getActiveCountWithCompletion:(void (^ _Nonnull)(NSInteger))completion;
/// Cancel all scheduling
- (void)cancelAllSchedulingWithCompletion:(void (^ _Nullable)(void))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(int32_t, CTLogType, open) {
  CTLogTypeInfo = 0,
  CTLogTypeDebug = 1,
};

@class NSException;
SWIFT_CLASS_NAMED("CTLogger")
@interface CTLogger : NSObject
+ (void)setDebugLevel:(int32_t)level;
+ (int32_t)getDebugLevel SWIFT_WARN_UNUSED_RESULT;
+ (void)logWithLevel:(int32_t)level type:(int32_t)type message:(NSString * _Nonnull)message;
+ (void)logInternalError:(NSException * _Nonnull)exception;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Protocol for extracting type-specific data from in-apps
SWIFT_PROTOCOL("_TtP12CleverTapSDK18InAppDataExtractor_")
@protocol InAppDataExtractor
- (NSTimeInterval)extractDelayInApp:(NSDictionary<NSString *, id> * _Nonnull)inApp SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createSuccessResultWithId:(NSString * _Nonnull)id data:(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createErrorResultWithId:(NSString * _Nonnull)id message:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createDiscardedResultWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
@end

/// Data extractor for delayed in-apps
SWIFT_CLASS("_TtC12CleverTapSDK25DelayedInAppDataExtractor")
@interface DelayedInAppDataExtractor : NSObject <InAppDataExtractor>
- (NSTimeInterval)extractDelayInApp:(NSDictionary<NSString *, id> * _Nonnull)inApp SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createSuccessResultWithId:(NSString * _Nonnull)id data:(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createErrorResultWithId:(NSString * _Nonnull)id message:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createDiscardedResultWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP12CleverTapSDK22InAppSelectionStrategy_")
@protocol InAppSelectionStrategy
/// Selects eligible in-apps based on strategy-specific logic.
/// This is the core differentiator between Immediate and Delayed strategies.
/// @param sortedInApps List of in-apps already sorted by priority (highest first)
/// @param suppressionHandler Handler that checks and applies suppression, returns true if suppressed
/// @return List of selected in-apps for display/scheduling
- (NSArray<NSDictionary *> * _Nonnull)selectInApps:(NSArray<NSDictionary *> * _Nonnull)sortedInApps suppressionHandler:(BOOL (^ _Nonnull)(NSDictionary * _Nonnull))suppressionHandler SWIFT_WARN_UNUSED_RESULT;
/// Determines whether TTL should be updated during evaluation.
/// @return true if TTL should be updated now, false if deferred to display time
- (BOOL)shouldUpdateTTL SWIFT_WARN_UNUSED_RESULT;
@end

/// Strategy for delayed in-app evaluation and scheduling.
SWIFT_CLASS("_TtC12CleverTapSDK29DelayedInAppSelectionStrategy")
@interface DelayedInAppSelectionStrategy : NSObject <InAppSelectionStrategy>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DelayedInAppSelectionStrategy * _Nonnull shared;)
+ (DelayedInAppSelectionStrategy * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (BOOL)shouldUpdateTTL SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSDictionary *> * _Nonnull)selectInApps:(NSArray<NSDictionary *> * _Nonnull)sortedInApps suppressionHandler:(BOOL (^ _Nonnull)(NSDictionary * _Nonnull))suppressionHandler SWIFT_WARN_UNUSED_RESULT;
@end

/// Strategy protocol for handling storage operations before/after scheduling
SWIFT_PROTOCOL("_TtP12CleverTapSDK23InAppSchedulingStrategy_")
@protocol InAppSchedulingStrategy
/// Prepare data before scheduling (e.g., save to DB)
/// \param inApps Array of in-app dictionaries
///
///
/// returns:
/// true if preparation successful, false otherwise
- (BOOL)prepareForSchedulingInApps:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)inApps SWIFT_WARN_UNUSED_RESULT;
/// Retrieve data after timer completes
/// \param id Timer identifier
///
///
/// returns:
/// Dictionary if found, nil otherwise
- (NSDictionary<NSString *, id> * _Nullable)retrieveAfterTimerWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Clear all stored data
- (void)clearAll;
@end

@class CTInAppStore;
/// Storage strategy for delayed in-apps (requires database persistence)
SWIFT_CLASS("_TtC12CleverTapSDK27DelayedInAppStorageStrategy")
@interface DelayedInAppStorageStrategy : NSObject <InAppSchedulingStrategy>
@property (nonatomic, strong) CTInAppStore * _Nullable delayedLegacyInAppStore;
- (nonnull instancetype)initWithDelayedLegacyInAppStore:(CTInAppStore * _Nullable)delayedLegacyInAppStore OBJC_DESIGNATED_INITIALIZER;
- (BOOL)prepareForSchedulingInApps:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)inApps SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)retrieveAfterTimerWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (void)clearAll;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Protocol representing in-app notifications partitioned by their display duration.
/// Duration types:
/// <ul>
///   <li>
///     <em>Immediate</em>: No delay, display right away
///   </li>
///   <li>
///     <em>Delayed</em>: Has <code>delayAfterTrigger</code>, display after specified seconds
///   </li>
///   <li>
///     <em>InAction</em>: Has <code>inactionDuration</code>, fetch content after user inactivity timer
///   </li>
///   <li>
///     <em>Unknown</em>: Actual duration (immediate/delayed) determined later via eval flow
///   </li>
/// </ul>
/// Conforming types:
/// <ul>
///   <li>
///     <code>ImmediateAndDelayed</code>: For Legacy, Client-Side, and AppLaunch Server-Side in-apps
///   </li>
///   <li>
///     <code>UnknownAndInAction</code>: For Server-Side metadata in-apps
///   </li>
///   <li>
///     <code>InActionOnly</code>: For Legacy metadata and AppLaunch Server-Side metadata in-apps
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP12CleverTapSDK25DurationPartitionedInApps_")
@protocol DurationPartitionedInApps
@end

/// Partition containing immediate and delayed duration in-apps.
/// Used for:
/// <ul>
///   <li>
///     Legacy in-apps (<code>inapp_notifs</code>)
///   </li>
///   <li>
///     Client-Side in-apps (<code>inapp_notifs_cs</code>)
///   </li>
///   <li>
///     AppLaunch Server-Side in-apps (<code>inapp_notifs_applaunched</code>)
///   </li>
/// </ul>
/// Note: These sources do NOT contain <code>inactionDuration</code> items.
/// InAction items come separately in their respective <code>_meta</code> keys.
SWIFT_CLASS("_TtC12CleverTapSDK19ImmediateAndDelayed")
@interface ImmediateAndDelayed : NSObject <DurationPartitionedInApps>
@property (nonatomic, readonly, strong) NSArray * _Nonnull immediateInApps;
@property (nonatomic, readonly, strong) NSArray * _Nonnull delayedInApps;
- (nonnull instancetype)initWithImmediateInApps:(NSArray * _Nonnull)immediateInApps delayedInApps:(NSArray * _Nonnull)delayedInApps OBJC_DESIGNATED_INITIALIZER;
- (BOOL)hasImmediateInApps SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasDelayedInApps SWIFT_WARN_UNUSED_RESULT;
+ (ImmediateAndDelayed * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Strategy for immediate in-app evaluation and display.
/// <ul>
///   <li>
///     Updates TTL at evaluation time (for client-side only)
///   </li>
///   <li>
///     Returns only the first non-suppressed in-app
///   </li>
///   <li>
///     Used for both client-side and app launch server-side immediate in-apps
///   </li>
/// </ul>
SWIFT_CLASS("_TtC12CleverTapSDK31ImmediateInAppSelectionStrategy")
@interface ImmediateInAppSelectionStrategy : NSObject <InAppSelectionStrategy>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ImmediateInAppSelectionStrategy * _Nonnull shared;)
+ (ImmediateInAppSelectionStrategy * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (BOOL)shouldUpdateTTL SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSDictionary *> * _Nonnull)selectInApps:(NSArray<NSDictionary *> * _Nonnull)sortedInApps suppressionHandler:(BOOL (^ _Nonnull)(NSDictionary * _Nonnull))suppressionHandler SWIFT_WARN_UNUSED_RESULT;
@end

/// Data extractor for in-action in-apps
SWIFT_CLASS("_TtC12CleverTapSDK21InActionDataExtractor")
@interface InActionDataExtractor : NSObject <InAppDataExtractor>
- (NSTimeInterval)extractDelayInApp:(NSDictionary<NSString *, id> * _Nonnull)inApp SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createSuccessResultWithId:(NSString * _Nonnull)id data:(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createErrorResultWithId:(NSString * _Nonnull)id message:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createDiscardedResultWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createCancelledResultWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Partition containing only inAction duration in-apps.
/// Used for:
/// <ul>
///   <li>
///     Legacy metadata in-apps (<code>inapp_notifs_meta</code>)
///   </li>
///   <li>
///     AppLaunch Server-Side metadata in-apps (<code>inapp_notifs_applaunched_meta</code>)
///   </li>
/// </ul>
/// All items have <code>inactionDuration</code> → fetch content after inactivity timer.
SWIFT_CLASS("_TtC12CleverTapSDK12InActionOnly")
@interface InActionOnly : NSObject <DurationPartitionedInApps>
@property (nonatomic, readonly, strong) NSArray * _Nonnull inActionInApps;
- (nonnull instancetype)initInActionInApps:(NSArray * _Nonnull)inActionInApps OBJC_DESIGNATED_INITIALIZER;
- (BOOL)hasInActionInApps SWIFT_WARN_UNUSED_RESULT;
+ (InActionOnly * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Constants for in-app delay configuration
SWIFT_CLASS("_TtC12CleverTapSDK19InAppDelayConstants")
@interface InAppDelayConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull INAPP_DELAY_AFTER_TRIGGER;)
+ (NSString * _Nonnull)INAPP_DELAY_AFTER_TRIGGER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull INAPP_ID_IN_PAYLOAD;)
+ (NSString * _Nonnull)INAPP_ID_IN_PAYLOAD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_MIN_DELAY_SECONDS;)
+ (NSInteger)INAPP_MIN_DELAY_SECONDS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_MAX_DELAY_SECONDS;)
+ (NSInteger)INAPP_MAX_DELAY_SECONDS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_DEFAULT_DELAY_SECONDS;)
+ (NSInteger)INAPP_DEFAULT_DELAY_SECONDS SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UnknownAndInAction;
/// Utility class for partitioning in-app notifications by their display duration.
/// Duration categories:
/// <ul>
///   <li>
///     <em>Immediate</em>: duration = 0, no delay fields present
///   </li>
///   <li>
///     <em>Delayed</em>: has valid <code>delayAfterTrigger</code> (1-1200 seconds)
///   </li>
///   <li>
///     <em>InAction</em>: has valid <code>inactionDuration</code> (1-1200 seconds)
///   </li>
///   <li>
///     <em>Unknown</em>: actual duration determined later via eval flow (used for SS meta)
///   </li>
/// </ul>
/// Provides specialized partition functions for different in-app sources:
/// <ul>
///   <li>
///     <code>partitionLegacyInApps</code>: immediate + delayed
///   </li>
///   <li>
///     <code>partitionLegacyMetaInApps</code>: inAction only
///   </li>
///   <li>
///     <code>partitionClientSideInApps</code>: immediate + delayed
///   </li>
///   <li>
///     <code>partitionServerSideMetaInApps</code>: unknown + inAction
///   </li>
///   <li>
///     <code>partitionAppLaunchServerSideInApps</code>: immediate + delayed
///   </li>
///   <li>
///     <code>partitionAppLaunchServerSideMetaInApps</code>: inAction only
///   </li>
/// </ul>
SWIFT_CLASS("_TtC12CleverTapSDK24InAppDurationPartitioner")
@interface InAppDurationPartitioner : NSObject
/// Partitions legacy in-apps by duration: immediate and delayed.
/// Note: This source does NOT contain <code>inactionDuration</code> items.
/// InAction items come separately in <code>inapp_notifs_meta</code>.
/// @param inAppsArray The array of legacy in-app notifications
/// @return ImmediateAndDelayed containing partitioned in-apps
+ (ImmediateAndDelayed * _Nonnull)partitionImmediateDelayedInApps:(NSArray * _Nullable)inAppsArray SWIFT_WARN_UNUSED_RESULT;
/// Wraps legacy metadata in-apps as inAction only.
/// All items in <code>inapp_notifs_meta</code> have <code>inactionDuration</code>
/// → fetch content after inactivity timer.
/// Note: No partitioning needed as all items are inAction.
/// @param inAppsArray The array of legacy metadata in-app notifications
/// @return InActionOnly containing inAction in-apps
+ (InActionOnly * _Nonnull)partitionLegacyMetaInApps:(NSArray * _Nullable)inAppsArray SWIFT_WARN_UNUSED_RESULT;
/// Partitions server-side metadata in-apps by duration: unknown and inAction.
/// <ul>
///   <li>
///     <em>Unknown</em>: No <code>inactionDuration</code> → goes through <code>inApps_eval</code> flow
///     → actual duration (immediate/delayed) determined after eval response
///   </li>
///   <li>
///     <em>InAction</em>: Has <code>inactionDuration</code> → fetch content after inactivity timer
///   </li>
/// </ul>
/// Note: Server-side meta does NOT have <code>delayAfterTrigger</code> directly
/// (delay info comes only after eval or inAction fetch).
/// @param inAppsArray The array of server-side metadata in-app notifications
/// @return UnknownAndInAction containing partitioned in-apps
+ (UnknownAndInAction * _Nonnull)partitionServerSideMetaInApps:(NSArray * _Nullable)inAppsArray SWIFT_WARN_UNUSED_RESULT;
/// Wraps app-launch server-side metadata in-apps as inAction only.
/// All items in <code>inapp_notifs_applaunched_meta</code> have <code>inactionDuration</code>
/// → fetch content after inactivity timer.
/// Note: No partitioning needed as all items are inAction.
/// @param inAppsArray The array of app-launch server-side metadata in-app notifications
/// @return InActionOnly containing inAction in-apps
+ (InActionOnly * _Nonnull)partitionAppLaunchServerSideMetaInApps:(NSArray * _Nullable)inAppsArray SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Constants for in-app inaction configuration
SWIFT_CLASS("_TtC12CleverTapSDK22InAppInActionConstants")
@interface InAppInActionConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull INAPP_INACTION_DURATION;)
+ (NSString * _Nonnull)INAPP_INACTION_DURATION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_MIN_INACTION_SECONDS;)
+ (NSInteger)INAPP_MIN_INACTION_SECONDS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_MAX_INACTION_SECONDS;)
+ (NSInteger)INAPP_MAX_INACTION_SECONDS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_DEFAULT_INACTION_SECONDS;)
+ (NSInteger)INAPP_DEFAULT_INACTION_SECONDS SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Core timer manager that handles scheduling, lifecycle, and callback management
/// This is the reusable component for both delay and in-action features
SWIFT_CLASS("_TtC12CleverTapSDK17InAppTimerManager")
@interface InAppTimerManager : NSObject
- (nonnull instancetype)initWithTagSuffix:(NSString * _Nonnull)tagSuffix OBJC_DESIGNATED_INITIALIZER;
- (BOOL)cancelTimerWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Cancel all active timers (without storing cancelled state)
- (void)cancelAllTimers;
/// Check if a timer is scheduled and active
- (BOOL)isTimerScheduledWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Cleanup all timer state
- (void)cleanup;
/// Get count of active timers
- (NSInteger)getActiveTimerCount SWIFT_WARN_UNUSED_RESULT;
/// App went to background - cancel all timers
- (void)onAppBackground;
/// App came to foreground - reschedule cancelled timers with remaining time
- (void)onAppForeground;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Storage strategy for delayed in-apps (requires database persistence)
SWIFT_CLASS("_TtC12CleverTapSDK28InactionInAppStorageStrategy")
@interface InactionInAppStorageStrategy : NSObject <InAppSchedulingStrategy>
- (BOOL)prepareForSchedulingInApps:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)inApps SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)retrieveAfterTimerWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (void)clearAll;
- (NSInteger)getCacheSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12CleverTapSDK24NetworkEncryptionManager")
@interface NetworkEncryptionManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NetworkEncryptionManager * _Nonnull shared;)
+ (NetworkEncryptionManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ITP;)
+ (NSString * _Nonnull)ITP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ITK;)
+ (NSString * _Nonnull)ITK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ITV;)
+ (NSString * _Nonnull)ITV SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSString * _Nullable)getSessionKeyBase64 SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)encryptWithObject:(id _Nonnull)object SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nonnull)decryptWithResponseData:(NSData * _Nonnull)responseData SWIFT_WARN_UNUSED_RESULT;
@end

/// Partition containing unknown and inAction duration in-apps.
/// Used for:
/// <ul>
///   <li>
///     Server-Side metadata in-apps (<code>inapp_notifs_ss</code>)
///   </li>
///   <li>
///     <em>Unknown</em>: No <code>inactionDuration</code> → goes through <code>inApps_eval</code> flow
///     → actual duration (immediate/delayed) determined after eval response
///   </li>
///   <li>
///     <em>InAction</em>: Has <code>inactionDuration</code> → fetch content after inactivity timer
///   </li>
/// </ul>
SWIFT_CLASS("_TtC12CleverTapSDK18UnknownAndInAction")
@interface UnknownAndInAction : NSObject <DurationPartitionedInApps>
@property (nonatomic, readonly, strong) NSArray * _Nonnull unknownDurationInApps;
@property (nonatomic, readonly, strong) NSArray * _Nonnull inActionInApps;
- (nonnull instancetype)initWithUnknownDurationInApps:(NSArray * _Nonnull)unknownDurationInApps inActionInApps:(NSArray * _Nonnull)inActionInApps OBJC_DESIGNATED_INITIALIZER;
- (BOOL)hasUnknownDurationInApps SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasInActionInApps SWIFT_WARN_UNUSED_RESULT;
+ (UnknownAndInAction * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef CLEVERTAPSDK_SWIFT_H
#define CLEVERTAPSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CleverTapSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class NSError;
@class NSData;
SWIFT_CLASS_NAMED("AESGCMCrypt") SWIFT_AVAILABILITY(tvos,introduced=13.0) SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface CTAESGCMCrypt : NSObject
- (nonnull instancetype)initWithKeychainTag:(NSString * _Nonnull)keychainTag OBJC_DESIGNATED_INITIALIZER;
/// Encrypts a string and returns a base64 encoded string with a prefix and suffix.
- (NSString * _Nullable)encryptString:(NSString * _Nonnull)message error:(NSError * _Nullable * _Nullable)errorPointer SWIFT_WARN_UNUSED_RESULT;
/// Encrypts data using AES-GCM and returns a formatted string.
- (NSString * _Nullable)encryptData:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)errorPointer SWIFT_WARN_UNUSED_RESULT;
/// Decrypts an encrypted string and returns the original string.
- (NSString * _Nullable)decryptString:(NSString * _Nonnull)encryptedString error:(NSError * _Nullable * _Nullable)errorPointer SWIFT_WARN_UNUSED_RESULT;
/// Decrypts an encrypted string and returns the original data.
- (NSData * _Nullable)decryptData:(NSString * _Nonnull)encryptedString error:(NSError * _Nullable * _Nullable)errorPointer SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("CTAppRatingHelper")
@interface CTAppRatingHelper : NSObject
+ (void)requestRatingWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CTTimerResult;
SWIFT_CLASS("_TtC12CleverTapSDK18CTCancelledJobData")
@interface CTCancelledJobData : NSObject
@property (nonatomic, readonly) NSTimeInterval originalDelay;
@property (nonatomic, readonly) NSTimeInterval scheduledAt;
- (nonnull instancetype)initWithOriginalDelay:(NSTimeInterval)originalDelay scheduledAt:(NSTimeInterval)scheduledAt callback:(void (^ _Nonnull)(CTTimerResult * _Nonnull))callback OBJC_DESIGNATED_INITIALIZER;
- (void)invokeCallbackWith:(CTTimerResult * _Nonnull)result;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class InAppTimerManager;
@protocol InAppSchedulingStrategy;
@protocol InAppDataExtractor;
/// Unified scheduler that combines timer management with storage strategy
/// Can be used for both delayed and in-action features
SWIFT_CLASS("_TtC12CleverTapSDK16CTInAppScheduler")
@interface CTInAppScheduler : NSObject
- (nonnull instancetype)initWithTimerManager:(InAppTimerManager * _Nonnull)timerManager storageStrategy:(id <InAppSchedulingStrategy> _Nullable)storageStrategy dataExtractor:(id <InAppDataExtractor> _Nullable)dataExtractor OBJC_DESIGNATED_INITIALIZER;
/// Schedule multiple in-apps with appropriate storage strategy
- (void)scheduleInApps:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)inApps onComplete:(void (^ _Nonnull)(id _Nullable))onComplete;
/// Get active count
- (void)getActiveCountWithCompletion:(void (^ _Nonnull)(NSInteger))completion;
/// Cancel all scheduling
- (void)cancelAllSchedulingWithCompletion:(void (^ _Nullable)(void))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(int32_t, CTLogType, open) {
  CTLogTypeInfo = 0,
  CTLogTypeDebug = 1,
};

@class NSException;
SWIFT_CLASS_NAMED("CTLogger")
@interface CTLogger : NSObject
+ (void)setDebugLevel:(int32_t)level;
+ (int32_t)getDebugLevel SWIFT_WARN_UNUSED_RESULT;
+ (void)logWithLevel:(int32_t)level type:(int32_t)type message:(NSString * _Nonnull)message;
+ (void)logInternalError:(NSException * _Nonnull)exception;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Protocol for extracting type-specific data from in-apps
SWIFT_PROTOCOL("_TtP12CleverTapSDK18InAppDataExtractor_")
@protocol InAppDataExtractor
- (NSTimeInterval)extractDelayInApp:(NSDictionary<NSString *, id> * _Nonnull)inApp SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createSuccessResultWithId:(NSString * _Nonnull)id data:(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createErrorResultWithId:(NSString * _Nonnull)id message:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createDiscardedResultWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
@end

/// Data extractor for delayed in-apps
SWIFT_CLASS("_TtC12CleverTapSDK25DelayedInAppDataExtractor")
@interface DelayedInAppDataExtractor : NSObject <InAppDataExtractor>
- (NSTimeInterval)extractDelayInApp:(NSDictionary<NSString *, id> * _Nonnull)inApp SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createSuccessResultWithId:(NSString * _Nonnull)id data:(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createErrorResultWithId:(NSString * _Nonnull)id message:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createDiscardedResultWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP12CleverTapSDK22InAppSelectionStrategy_")
@protocol InAppSelectionStrategy
/// Selects eligible in-apps based on strategy-specific logic.
/// This is the core differentiator between Immediate and Delayed strategies.
/// @param sortedInApps List of in-apps already sorted by priority (highest first)
/// @param suppressionHandler Handler that checks and applies suppression, returns true if suppressed
/// @return List of selected in-apps for display/scheduling
- (NSArray<NSDictionary *> * _Nonnull)selectInApps:(NSArray<NSDictionary *> * _Nonnull)sortedInApps suppressionHandler:(BOOL (^ _Nonnull)(NSDictionary * _Nonnull))suppressionHandler SWIFT_WARN_UNUSED_RESULT;
/// Determines whether TTL should be updated during evaluation.
/// @return true if TTL should be updated now, false if deferred to display time
- (BOOL)shouldUpdateTTL SWIFT_WARN_UNUSED_RESULT;
@end

/// Strategy for delayed in-app evaluation and scheduling.
SWIFT_CLASS("_TtC12CleverTapSDK29DelayedInAppSelectionStrategy")
@interface DelayedInAppSelectionStrategy : NSObject <InAppSelectionStrategy>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DelayedInAppSelectionStrategy * _Nonnull shared;)
+ (DelayedInAppSelectionStrategy * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (BOOL)shouldUpdateTTL SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSDictionary *> * _Nonnull)selectInApps:(NSArray<NSDictionary *> * _Nonnull)sortedInApps suppressionHandler:(BOOL (^ _Nonnull)(NSDictionary * _Nonnull))suppressionHandler SWIFT_WARN_UNUSED_RESULT;
@end

/// Strategy protocol for handling storage operations before/after scheduling
SWIFT_PROTOCOL("_TtP12CleverTapSDK23InAppSchedulingStrategy_")
@protocol InAppSchedulingStrategy
/// Prepare data before scheduling (e.g., save to DB)
/// \param inApps Array of in-app dictionaries
///
///
/// returns:
/// true if preparation successful, false otherwise
- (BOOL)prepareForSchedulingInApps:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)inApps SWIFT_WARN_UNUSED_RESULT;
/// Retrieve data after timer completes
/// \param id Timer identifier
///
///
/// returns:
/// Dictionary if found, nil otherwise
- (NSDictionary<NSString *, id> * _Nullable)retrieveAfterTimerWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Clear all stored data
- (void)clearAll;
@end

@class CTInAppStore;
/// Storage strategy for delayed in-apps (requires database persistence)
SWIFT_CLASS("_TtC12CleverTapSDK27DelayedInAppStorageStrategy")
@interface DelayedInAppStorageStrategy : NSObject <InAppSchedulingStrategy>
@property (nonatomic, strong) CTInAppStore * _Nullable delayedLegacyInAppStore;
- (nonnull instancetype)initWithDelayedLegacyInAppStore:(CTInAppStore * _Nullable)delayedLegacyInAppStore OBJC_DESIGNATED_INITIALIZER;
- (BOOL)prepareForSchedulingInApps:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)inApps SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)retrieveAfterTimerWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (void)clearAll;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Protocol representing in-app notifications partitioned by their display duration.
/// Duration types:
/// <ul>
///   <li>
///     <em>Immediate</em>: No delay, display right away
///   </li>
///   <li>
///     <em>Delayed</em>: Has <code>delayAfterTrigger</code>, display after specified seconds
///   </li>
///   <li>
///     <em>InAction</em>: Has <code>inactionDuration</code>, fetch content after user inactivity timer
///   </li>
///   <li>
///     <em>Unknown</em>: Actual duration (immediate/delayed) determined later via eval flow
///   </li>
/// </ul>
/// Conforming types:
/// <ul>
///   <li>
///     <code>ImmediateAndDelayed</code>: For Legacy, Client-Side, and AppLaunch Server-Side in-apps
///   </li>
///   <li>
///     <code>UnknownAndInAction</code>: For Server-Side metadata in-apps
///   </li>
///   <li>
///     <code>InActionOnly</code>: For Legacy metadata and AppLaunch Server-Side metadata in-apps
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP12CleverTapSDK25DurationPartitionedInApps_")
@protocol DurationPartitionedInApps
@end

/// Partition containing immediate and delayed duration in-apps.
/// Used for:
/// <ul>
///   <li>
///     Legacy in-apps (<code>inapp_notifs</code>)
///   </li>
///   <li>
///     Client-Side in-apps (<code>inapp_notifs_cs</code>)
///   </li>
///   <li>
///     AppLaunch Server-Side in-apps (<code>inapp_notifs_applaunched</code>)
///   </li>
/// </ul>
/// Note: These sources do NOT contain <code>inactionDuration</code> items.
/// InAction items come separately in their respective <code>_meta</code> keys.
SWIFT_CLASS("_TtC12CleverTapSDK19ImmediateAndDelayed")
@interface ImmediateAndDelayed : NSObject <DurationPartitionedInApps>
@property (nonatomic, readonly, strong) NSArray * _Nonnull immediateInApps;
@property (nonatomic, readonly, strong) NSArray * _Nonnull delayedInApps;
- (nonnull instancetype)initWithImmediateInApps:(NSArray * _Nonnull)immediateInApps delayedInApps:(NSArray * _Nonnull)delayedInApps OBJC_DESIGNATED_INITIALIZER;
- (BOOL)hasImmediateInApps SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasDelayedInApps SWIFT_WARN_UNUSED_RESULT;
+ (ImmediateAndDelayed * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Strategy for immediate in-app evaluation and display.
/// <ul>
///   <li>
///     Updates TTL at evaluation time (for client-side only)
///   </li>
///   <li>
///     Returns only the first non-suppressed in-app
///   </li>
///   <li>
///     Used for both client-side and app launch server-side immediate in-apps
///   </li>
/// </ul>
SWIFT_CLASS("_TtC12CleverTapSDK31ImmediateInAppSelectionStrategy")
@interface ImmediateInAppSelectionStrategy : NSObject <InAppSelectionStrategy>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ImmediateInAppSelectionStrategy * _Nonnull shared;)
+ (ImmediateInAppSelectionStrategy * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (BOOL)shouldUpdateTTL SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSDictionary *> * _Nonnull)selectInApps:(NSArray<NSDictionary *> * _Nonnull)sortedInApps suppressionHandler:(BOOL (^ _Nonnull)(NSDictionary * _Nonnull))suppressionHandler SWIFT_WARN_UNUSED_RESULT;
@end

/// Data extractor for in-action in-apps
SWIFT_CLASS("_TtC12CleverTapSDK21InActionDataExtractor")
@interface InActionDataExtractor : NSObject <InAppDataExtractor>
- (NSTimeInterval)extractDelayInApp:(NSDictionary<NSString *, id> * _Nonnull)inApp SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createSuccessResultWithId:(NSString * _Nonnull)id data:(NSDictionary<NSString *, id> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createErrorResultWithId:(NSString * _Nonnull)id message:(NSString * _Nonnull)message SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createDiscardedResultWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (id _Nonnull)createCancelledResultWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Partition containing only inAction duration in-apps.
/// Used for:
/// <ul>
///   <li>
///     Legacy metadata in-apps (<code>inapp_notifs_meta</code>)
///   </li>
///   <li>
///     AppLaunch Server-Side metadata in-apps (<code>inapp_notifs_applaunched_meta</code>)
///   </li>
/// </ul>
/// All items have <code>inactionDuration</code> → fetch content after inactivity timer.
SWIFT_CLASS("_TtC12CleverTapSDK12InActionOnly")
@interface InActionOnly : NSObject <DurationPartitionedInApps>
@property (nonatomic, readonly, strong) NSArray * _Nonnull inActionInApps;
- (nonnull instancetype)initInActionInApps:(NSArray * _Nonnull)inActionInApps OBJC_DESIGNATED_INITIALIZER;
- (BOOL)hasInActionInApps SWIFT_WARN_UNUSED_RESULT;
+ (InActionOnly * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Constants for in-app delay configuration
SWIFT_CLASS("_TtC12CleverTapSDK19InAppDelayConstants")
@interface InAppDelayConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull INAPP_DELAY_AFTER_TRIGGER;)
+ (NSString * _Nonnull)INAPP_DELAY_AFTER_TRIGGER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull INAPP_ID_IN_PAYLOAD;)
+ (NSString * _Nonnull)INAPP_ID_IN_PAYLOAD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_MIN_DELAY_SECONDS;)
+ (NSInteger)INAPP_MIN_DELAY_SECONDS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_MAX_DELAY_SECONDS;)
+ (NSInteger)INAPP_MAX_DELAY_SECONDS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_DEFAULT_DELAY_SECONDS;)
+ (NSInteger)INAPP_DEFAULT_DELAY_SECONDS SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UnknownAndInAction;
/// Utility class for partitioning in-app notifications by their display duration.
/// Duration categories:
/// <ul>
///   <li>
///     <em>Immediate</em>: duration = 0, no delay fields present
///   </li>
///   <li>
///     <em>Delayed</em>: has valid <code>delayAfterTrigger</code> (1-1200 seconds)
///   </li>
///   <li>
///     <em>InAction</em>: has valid <code>inactionDuration</code> (1-1200 seconds)
///   </li>
///   <li>
///     <em>Unknown</em>: actual duration determined later via eval flow (used for SS meta)
///   </li>
/// </ul>
/// Provides specialized partition functions for different in-app sources:
/// <ul>
///   <li>
///     <code>partitionLegacyInApps</code>: immediate + delayed
///   </li>
///   <li>
///     <code>partitionLegacyMetaInApps</code>: inAction only
///   </li>
///   <li>
///     <code>partitionClientSideInApps</code>: immediate + delayed
///   </li>
///   <li>
///     <code>partitionServerSideMetaInApps</code>: unknown + inAction
///   </li>
///   <li>
///     <code>partitionAppLaunchServerSideInApps</code>: immediate + delayed
///   </li>
///   <li>
///     <code>partitionAppLaunchServerSideMetaInApps</code>: inAction only
///   </li>
/// </ul>
SWIFT_CLASS("_TtC12CleverTapSDK24InAppDurationPartitioner")
@interface InAppDurationPartitioner : NSObject
/// Partitions legacy in-apps by duration: immediate and delayed.
/// Note: This source does NOT contain <code>inactionDuration</code> items.
/// InAction items come separately in <code>inapp_notifs_meta</code>.
/// @param inAppsArray The array of legacy in-app notifications
/// @return ImmediateAndDelayed containing partitioned in-apps
+ (ImmediateAndDelayed * _Nonnull)partitionImmediateDelayedInApps:(NSArray * _Nullable)inAppsArray SWIFT_WARN_UNUSED_RESULT;
/// Wraps legacy metadata in-apps as inAction only.
/// All items in <code>inapp_notifs_meta</code> have <code>inactionDuration</code>
/// → fetch content after inactivity timer.
/// Note: No partitioning needed as all items are inAction.
/// @param inAppsArray The array of legacy metadata in-app notifications
/// @return InActionOnly containing inAction in-apps
+ (InActionOnly * _Nonnull)partitionLegacyMetaInApps:(NSArray * _Nullable)inAppsArray SWIFT_WARN_UNUSED_RESULT;
/// Partitions server-side metadata in-apps by duration: unknown and inAction.
/// <ul>
///   <li>
///     <em>Unknown</em>: No <code>inactionDuration</code> → goes through <code>inApps_eval</code> flow
///     → actual duration (immediate/delayed) determined after eval response
///   </li>
///   <li>
///     <em>InAction</em>: Has <code>inactionDuration</code> → fetch content after inactivity timer
///   </li>
/// </ul>
/// Note: Server-side meta does NOT have <code>delayAfterTrigger</code> directly
/// (delay info comes only after eval or inAction fetch).
/// @param inAppsArray The array of server-side metadata in-app notifications
/// @return UnknownAndInAction containing partitioned in-apps
+ (UnknownAndInAction * _Nonnull)partitionServerSideMetaInApps:(NSArray * _Nullable)inAppsArray SWIFT_WARN_UNUSED_RESULT;
/// Wraps app-launch server-side metadata in-apps as inAction only.
/// All items in <code>inapp_notifs_applaunched_meta</code> have <code>inactionDuration</code>
/// → fetch content after inactivity timer.
/// Note: No partitioning needed as all items are inAction.
/// @param inAppsArray The array of app-launch server-side metadata in-app notifications
/// @return InActionOnly containing inAction in-apps
+ (InActionOnly * _Nonnull)partitionAppLaunchServerSideMetaInApps:(NSArray * _Nullable)inAppsArray SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Constants for in-app inaction configuration
SWIFT_CLASS("_TtC12CleverTapSDK22InAppInActionConstants")
@interface InAppInActionConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull INAPP_INACTION_DURATION;)
+ (NSString * _Nonnull)INAPP_INACTION_DURATION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_MIN_INACTION_SECONDS;)
+ (NSInteger)INAPP_MIN_INACTION_SECONDS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_MAX_INACTION_SECONDS;)
+ (NSInteger)INAPP_MAX_INACTION_SECONDS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger INAPP_DEFAULT_INACTION_SECONDS;)
+ (NSInteger)INAPP_DEFAULT_INACTION_SECONDS SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Core timer manager that handles scheduling, lifecycle, and callback management
/// This is the reusable component for both delay and in-action features
SWIFT_CLASS("_TtC12CleverTapSDK17InAppTimerManager")
@interface InAppTimerManager : NSObject
- (nonnull instancetype)initWithTagSuffix:(NSString * _Nonnull)tagSuffix OBJC_DESIGNATED_INITIALIZER;
- (BOOL)cancelTimerWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Cancel all active timers (without storing cancelled state)
- (void)cancelAllTimers;
/// Check if a timer is scheduled and active
- (BOOL)isTimerScheduledWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
/// Cleanup all timer state
- (void)cleanup;
/// Get count of active timers
- (NSInteger)getActiveTimerCount SWIFT_WARN_UNUSED_RESULT;
/// App went to background - cancel all timers
- (void)onAppBackground;
/// App came to foreground - reschedule cancelled timers with remaining time
- (void)onAppForeground;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Storage strategy for delayed in-apps (requires database persistence)
SWIFT_CLASS("_TtC12CleverTapSDK28InactionInAppStorageStrategy")
@interface InactionInAppStorageStrategy : NSObject <InAppSchedulingStrategy>
- (BOOL)prepareForSchedulingInApps:(NSArray<NSDictionary<NSString *, id> *> * _Nonnull)inApps SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nullable)retrieveAfterTimerWithId:(NSString * _Nonnull)id SWIFT_WARN_UNUSED_RESULT;
- (void)clearAll;
- (NSInteger)getCacheSize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12CleverTapSDK24NetworkEncryptionManager")
@interface NetworkEncryptionManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NetworkEncryptionManager * _Nonnull shared;)
+ (NetworkEncryptionManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ITP;)
+ (NSString * _Nonnull)ITP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ITK;)
+ (NSString * _Nonnull)ITK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ITV;)
+ (NSString * _Nonnull)ITV SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (NSString * _Nullable)getSessionKeyBase64 SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, id> * _Nonnull)encryptWithObject:(id _Nonnull)object SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nonnull)decryptWithResponseData:(NSData * _Nonnull)responseData SWIFT_WARN_UNUSED_RESULT;
@end

/// Partition containing unknown and inAction duration in-apps.
/// Used for:
/// <ul>
///   <li>
///     Server-Side metadata in-apps (<code>inapp_notifs_ss</code>)
///   </li>
///   <li>
///     <em>Unknown</em>: No <code>inactionDuration</code> → goes through <code>inApps_eval</code> flow
///     → actual duration (immediate/delayed) determined after eval response
///   </li>
///   <li>
///     <em>InAction</em>: Has <code>inactionDuration</code> → fetch content after inactivity timer
///   </li>
/// </ul>
SWIFT_CLASS("_TtC12CleverTapSDK18UnknownAndInAction")
@interface UnknownAndInAction : NSObject <DurationPartitionedInApps>
@property (nonatomic, readonly, strong) NSArray * _Nonnull unknownDurationInApps;
@property (nonatomic, readonly, strong) NSArray * _Nonnull inActionInApps;
- (nonnull instancetype)initWithUnknownDurationInApps:(NSArray * _Nonnull)unknownDurationInApps inActionInApps:(NSArray * _Nonnull)inActionInApps OBJC_DESIGNATED_INITIALIZER;
- (BOOL)hasUnknownDurationInApps SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasInActionInApps SWIFT_WARN_UNUSED_RESULT;
+ (UnknownAndInAction * _Nonnull)empty SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
