
platform :ios, '10.0'

target 'ObjCStarter' do
  
  use_frameworks!

  # Pods for ObjCStarter
  pod 'CleverTap-iOS-SDK', :path =>'../'

  target 'ObjCStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObjCStarterUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'ObjCTvOS' do
      platform :tvos, '9.0'
      pod 'CleverTap-iOS-SDK', :path =>'../'
  end
  
end
