name: Run Unit Tests

on:
  push:
    branches:
      - run-tests

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode and show Swift version
        run: |
          sudo xcode-select -s /Applications/Xcode_16.0.app
          swift --version

      - name: Show available simulators
        run: xcrun simctl list devices

      - name: Install CocoaPods dependencies
        run: pod install  

      - name: Run unit tests
        run: |
           xcodebuild test \
            -workspace CleverTapSDK.xcworkspace \
            -scheme CleverTapSDKTests \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO
