name: Run Unit Tests

on:
  push:
    branches:
      - run-tests

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode and show Swift version
        run: |
          sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
          swift --version

      - name: List available simulators
        run: xcrun simctl list devices
      
      - name: Install CocoaPods dependencies
        run: pod install

      - name: Install xcpretty
        run: gem install xcpretty
        
      - name: Run Tests
        run: |
           xcodebuild test \
            -workspace CleverTapSDK.xcworkspace \
            -scheme CleverTapSDKTests \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' \
            | xcpretty --simple